[project]
name = "her"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.6",
    "google-generativeai>=0.8.3",
    "python-dotenv>=1.0.1",
]
